#waifus--------------------------------------------------
waifu_sfw={
            'waifu': 'sfw/waifu',
            'neko': 'sfw/neko',
            'shinobu': 'sfw/shinobu',
            'megumin': 'sfw/megumin',
            'bully': 'sfw/bully',
            'cuddle': 'sfw/cuddle',
            'cry': 'sfw/cry',
            'hug': 'sfw/hug',
            'awoo': 'sfw/awoo',
            'kiss': 'sfw/kiss',
            'lick': 'sfw/lick',
            'pat': 'sfw/pat',
            'smug': 'sfw/smug',
            'bonk': 'sfw/bonk',
            'yeet': 'sfw/yeet',
            'blush': 'sfw/blush',
            'smile': 'sfw/smile',
            'wave': 'sfw/wave',
            'highfive': 'sfw/highfive',
            'handhold': 'sfw/handhold',
            'nom': 'sfw/nom',
            'bite': 'sfw/bite',
            'glomp': 'sfw/glomp',
            'kill': 'sfw/kill',
            'slap': 'sfw/slap',
            'happy': 'sfw/happy',
            'wink': 'sfw/wink',
            'poke': 'sfw/poke',
            'dance': 'sfw/dance',
            'cringe': 'sfw/cringe',
            'blush': 'sfw/blush'
        }

waifu_nsfw={
            'waifu': 'nsfw/waifu',
            'neko': 'nsfw/neko',
            'trap': 'nsfw/trap',
            'blowjob': 'nsfw/blowjob'
        }

#nekos--------------------------------------------------
neko_sfw={
            "tickle": "/img/tickle",
            "slap": "/img/slap",
            "poke": "/img/poke",
            "pat": "/img/pat",
            "neko": "/img/neko",
            "meow": "/img/meow",
            "lizard": "/img/lizard",
            "kiss": "/img/kiss",
            "hug": "/img/hug",
            "foxGirl": "/img/fox_girl",
            "feed": "/img/feed",
            "cuddle": "/img/cuddle",
            "why": "/why",
            "catText": "/cat",
            "OwOify": "/owoify",
            "8Ball": "/8ball",
            "fact": "/fact",
            "nekoGif": "/img/ngif",
            "kemonomimi": "/img/kemonomimi",
            "holo": "/img/holo",
            "smug": "/img/smug",
            "baka": "/img/baka",
            "woof": "/img/woof",
            "spoiler": "/spoiler",
            "wallpaper": "/img/wallpaper",
            "goose": "/img/goose",
            "gecg": "/img/gecg",
            "avatar": "/img/avatar",
            "waifu": "/img/waifu"
        }

neko_nsfw={
            "randomHentaiGif": "/img/Random_hentai_gif",
            "pussy": "/img/pussy",
            "nekoGif": "/img/nsfw_neko_gif",
            "neko": "/img/lewd",
            "lesbian": "/img/les",
            "kuni": "/img/kuni",
            "cumsluts": "/img/cum",
            "classic": "/img/classic",
            "boobs": "/img/boobs",
            "bJ": "/img/bj",
            "anal": "/img/anal",
            "avatar": "/img/nsfw_avatar",
            "yuri": "/img/yuri",
            "trap": "/img/trap",
            "tits": "/img/tits",
            "girlSoloGif": "/img/solog",
            "girlSolo": "/img/solo",
            "pussyWankGif": "/img/pwankg",
            "pussyArt": "/img/pussy_jpg",
            "kemonomimi": "/img/lewdkemo",
            "kitsune": "/img/lewdk",
            "keta": "/img/keta",
            "holo": "/img/hololewd",
            "holoEro": "/img/holoero",
            "hentai": "/img/hentai",
            "futanari": "/img/futanari",
            "femdom": "/img/femdom",
            "feetGif": "/img/feetg",
            "eroFeet": "/img/erofeet",
            "feet": "/img/feet",
            "ero": "/img/ero",
            "eroKitsune": "/img/erok",
            "eroKemonomimi": "/img/erokemo",
            "eroNeko": "/img/eron",
            "eroYuri": "/img/eroyuri",
            "cumArts": "/img/cum_jpg",
            "blowJob": "/img/blowjob",
            "spank": "/img/spank",
            "gasm": "/img/gasm"
        }